### ISSUE TITLE
failing to install package when trying through composer

### ISSUE THREAD

**Issue by subbe** [BradEstey/hipsupport#2]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - estey/hipsupport v1.0.0 requires hipchat/hipchat-php dev-master -> no matching package found.
    - estey/hipsupport 1.0.x-dev requires hipchat/hipchat-php dev-master -> no matching package found.
    - estey/hipsupport 1.0.x-dev requires hipchat/hipchat-php dev-master -> no matching package found.
    - Installation request for estey/hipsupport 1.0.*@dev -> satisfiable by estey/hipsupport[1.0.x-dev, v1.0.0].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by BradEstey** [comment]
Looks like HipChat added version tags when I wasn't looking. It should be working now.

**Comment by subbe** [comment]
managed to install the package on my application.

but failing when i try to init the application.
![screen shot 2014-11-02 at 4 37 59 pm](https://cloud.githubusercontent.com/assets/3587988/4874495/fcc45b5e-625a-11e4-8345-3b46dc1f2021.png)

any idea why?

i was following the sample codes provided on the git page.

thank you

**Comment by BradEstey** [comment]
Do a composer update, I had to change a few things in the service provider to get the package config file to work in Laravel 4.2.

**Comment by subbe** [comment]
Thanks a lot.

everything is working fine now :)
